# Dynamically generated by Terraform
export MODEL_BUCKET_PROD="stg-mlflow-models-mlops-zoomcamp-413093438819"
export PREDICTIONS_STREAM_NAME="stg_ride_predictions-mlops-zoomcamp"
export LAMBDA_FUNCTION="stg_ride_prediction_lambda_mlops-zoomcamp"

# Model artifacts bucket from previous weeks (experiment tracking)
export MODEL_BUCKET_DEV="mlflow-artifacts-remote433"

# Add profile and region to aws commands
: "${AWS_PROFILE:=default}"
: "${AWS_DEFAULT_REGION:=us-west-1}"

awsx() {
  aws --profile "$AWS_PROFILE" --region "$AWS_DEFAULT_REGION" "$@"
}

# # 1. Find the most recently modified object that lives under */artifacts/*
# LATEST_KEY=$(
#   aws s3api list-objects-v2 \
#     --bucket "$MODEL_BUCKET_DEV" \
#     --query '
#       Contents[?
#         contains(Key, `/artifacts/`)
#       ] | sort_by(@, &LastModified)[-1].Key
#     ' \
#     --output text
# )

# if [[ -z "$LATEST_KEY" || "$LATEST_KEY" == "None" ]]; then
#   echo "ERROR: No artifacts found in bucket ${MODEL_BUCKET_DEV}" >&2
#   exit 1
# fi

# echo "Latest artifact key:"
# echo "  $LATEST_KEY"

# # 2. Extract the run directory (strip /artifacts/...)
# LATEST_RUN_DIR=$(echo "$LATEST_KEY" | sed -E 's|(.*)/artifacts/.*|\1|')

# echo "Latest run directory:"
# echo "  $LATEST_RUN_DIR"

# # 3. Extract the MLflow RUN_ID (32 hex chars)
# RUN_ID=$(echo "$LATEST_RUN_DIR" | grep -oE '[0-9a-f]{32}' | head -n 1)

RUN_ID=$(aws s3api list-objects-v2 --bucket "$MODEL_BUCKET_DEV" --query 'Contents[?contains(Key, `/artifacts/`)] | sort_by(@, &LastModified)[-1].Key' --output text \
  | sed -E 's|(.*)/artifacts/.*|\1|' | grep -oE '[0-9a-f]{32}' | head -1)

[[ -z "$RUN_ID" ]] && { echo "ERROR: No artifacts in ${MODEL_BUCKET_DEV}" >&2; exit 1; }

export RUN_ID
echo "Resolved RUN_ID:"
echo "  $RUN_ID"

# This is NOT FOR PRODUCTION
# Copy the model artifacts to the newly created production bucket
awsx s3 sync s3://${MODEL_BUCKET_DEV} s3://${MODEL_BUCKET_PROD}

# Set the environment variables for the Lambda function
# CRITICAL: TEST_RUN must be False or unset for Lambda to write predictions to Kinesis
# If TEST_RUN=True, callbacks will be empty and no records will be written
variables="{MODEL_BUCKET=${MODEL_BUCKET_PROD}, PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}, RUN_ID=${RUN_ID}, TEST_RUN=False}"

# Update the Lambda function (config only; does not update the Docker image/code)
awsx lambda update-function-configuration \
    --function-name ${LAMBDA_FUNCTION} \
    --environment "Variables=${variables}"
