services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME:-ride_predictions}
      - RUN_ID=Test123
      - MODEL_LOCATION=/app/model
      - KINESIS_ENDPOINT_URL=http://kinesis:4566
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${HOME}/.aws:/root/.aws:ro"
      - "./model:/app/model:ro"
  kinesis:
    image: localstack/localstack:0.14.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis
